  # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_TAGS: ''



#appendCommitMessageToRunName:
#steps:
#- script: echo Hello, world!
#- script: echo $(A)
#
# displayName: 'Run a one-line script'
stages:
  - stage: A
    jobs:
      - job: A
        steps:
        - checkout: self
        -  task: CmdLine@2
           displayName: 'Install Python Dependencies'
           inputs:
            script: |
              sudo apt update
              sudo apt install -y python3 python3-pip
              python3 -m pip install --upgrade pip
              python3 -m pip install requests
              echo "Installing pyyaml..."
              pip install pyyaml

            
        - task: CmdLine@2
          inputs:
            script: |
              python Tag.py 
              echo "YAML Run"
              data=$(python -c "
              import yaml
              yaml.SafeLoader.yaml_implicit_resolvers.pop('=')
              with open('Tags.yaml', 'r') as file:
                  data = yaml.safe_load(file)
              print(data)
              print(data.get('imageTags', 'No imageTags found'))")
              
              echo "##vso[task.setvariable variable=IMAGE_TAGS;issecret=false]$data"
#        - task :CmdLine@2
#              echo "Using image tags: $(IMAGE_TAGS)"
#          displayName: 'Read image tags from YAML file and set pipeline variable'
