  # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_TAGS: ''



#appendCommitMessageToRunName:
#steps:
#- script: echo Hello, world!
#- script: echo $(A)
#
# displayName: 'Run a one-line script'
stages:
  - stage: A
    jobs:
      - job: A
        steps:
        - checkout: self
        -  task: CmdLine@2
           displayName: 'Install Python Dependencies'
           inputs:
            script: |
              sudo apt update
              sudo apt install -y python3 python3-pip
              python3 -m pip install --upgrade pip
              python3 -m pip install requests
              echo "Installing pyyaml..."
              pip install pyyaml

            
        - task: CmdLine@2
          inputs:
            script: |
              $Tag = python Tag.py
              echo $Tag 
              echo "YAML RUn"
              python -c "import yaml
              yaml.SafeLoader.yaml_implicit_resolvers.pop('=') 
              with open('Tags.yaml', 'r') as file:
                data = yaml.safe_load(file)"
              echo $data['tags']")
              echo "##vso[task.setvariable variable=IMAGE_TAGS;issecret=false]$tags"
          displayName: 'Read image tags from YAML file and set pipeline variable'

         
# Step 3: Use the set pipeline variable
        - script: |
            echo "Using image tags: $(IMAGE_TAGS)"
          displayName: 'Use image tags in pipeline step'
